//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoinceDetail
    {
        public string invoinceNo { get; set; }
        public int productId { get; set; }
        public Nullable<int> quanlityProduct { get; set; }
        public Nullable<int> unitPrice { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<int> totalDiscount { get; set; }
    
        public virtual Invoince Invoince { get; set; }
        public virtual Product Product { get; set; }
    }
}
