//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.InvoinceDetails = new HashSet<InvoinceDetail>();
        }
    
        public int productId { get; set; }
        public string productName { get; set; }
        public string image { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> discount { get; set; }
        public string description { get; set; }
        public Nullable<int> quanlity { get; set; }
        public string brand { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<bool> status { get; set; }
        public int categoryId { get; set; }
        public string userName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoinceDetail> InvoinceDetails { get; set; }
        public virtual Member Member { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
